name: CI for features

on:
  push:
    branches:
      - feature/*

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.15
    - run: |
        npm install -g yarn
        yarn install
    - name: Run linter
      run: yarn workspaces foreach run lint
      env:
        CI: true
    - name: Run prettier
      run: yarn run check-format
      env:
        CI: true
    - name: verify docs were not updated
      run: |
        git checkout develop
        git checkout -
        git diff develop HEAD --exit-code --quiet -- docs
