name: CI for releases

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.15
    - run: npm install -g yarn
    - name: Run linter
      run: |
        yarn install
        yarn workspaces foreach run lint
      env:
        CI: true
    - name: verify docs up to date
      run: |
        yarn all_docs
        git diff --exit-code --quiet ':(exclude)docs/api_project.js' ':(exclude)docs/api_project.json'
